server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///dbspringcloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  type-aliases-package: org.example.springcloud.entities
  mapper-locations: classpath:mapper/**/*.xml

eureka:
  client:
#    表示是否将自己注册进Eureka Server 默认为true
    register-with-eureka: true
#    是否从Eureka Server抓取已有的注册信息，默认为true。单节点无所谓，集群必须为true才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka  #单机版
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka   #集群版
  instance:
    instance-id: payment8001
    prefer-ip-address: true  #访问路径可以显示ip
#    Eureka客户端像服务端发送心跳的时间间隔，单位为秒 默认30
    lease-renewal-interval-in-seconds: 1
#    Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒 默认90 超时将剔除服务
    lease-expiration-duration-in-seconds: 2

logging:
  level:
    org.example.springcloud: debug